language: python
python:
  - 2.6
  - 2.7
install:
  - virtualenv /home/vagrant/virtualenv/python$TRAVIS_PYTHON_VERSION --system-site-packages
  - sudo ./tv/linux/helperscripts/ubuntu_oneiric_11_10.sh
script:
  - cd tv/linux && ./test.sh -v